### ISSUE TITLE
Some collections crash api

### ISSUE THREAD

**Issue by m4xx1m** [zseta/python-opensea#20]
I'm trying to get a pixelmon collection but this collection breaks the script [photo], this collection may be banned or removed because other non-existing collections work.
P.S. I'm use free api without token.

![image](https://user-images.githubusercontent.com/59927482/156416569-ec54c2be-63b2-4c6c-999d-2378a8efff8b.png)

Where script crash:
![image](https://user-images.githubusercontent.com/59927482/156416878-6cf5d7d7-ce07-4cba-931d-1964ca863f40.png)

**Comment by m4xx1m** [comment]
+ idk why the API sometimes returns heroku app error
![image](https://user-images.githubusercontent.com/59927482/156417916-c137534c-0555-4bb2-9904-1ae7ecc96379.png)

**Comment by cxheng315** [comment]
From what I saw, the requests failed because Opensea doesn't support that collection anymore
You may try to use another collection-slug
This wrapper is based on Opensea API, if the official API doesn't support anymore, it's useless to find through anymore
If you need this specific collection, you may try to look into Moralis API.
Please refer to the link below 
```
https://api.opensea.io/api/v1/collection/pixelmon/stats?format=api
```
